### ISSUE TITLE
Wrong behavior of "Don't recommend this channel" button

### ISSUE THREAD

**Issue by binhnguyenvo** [lozog/not-interested-youtube#1] opened 2024-09-13 02:22 UTC
I click on "Don't recommend this channel" button, but it shows the panel as "Report this channel".
Please refer to the attached image for more information.
+ Browser version: Firefox 130.0 (64-bit)
+ Browser Language: English (US)
+ Language identified and shown on Youtube: Vietnamese
+ Location (my country): Vietnam

![Bug 1](https://github.com/user-attachments/assets/f35d80ac-48b5-4937-a4f8-967128a32eee)

**Comment by lozog** [comment] 2024-09-16 14:37
@binhnguyenvo which page are you on in this screenshot?

**Comment by binhnguyenvo** [comment] 2024-09-16 16:30
I'm on the main page (home) of Youtube. It is very frequency to encounter this issue, especially new channels I haven't seen. At that time of this bug, 2 buttons (Not interested button and Don't recommend button are two wrong behaviors:
  + "Not interested" button : it turns to "Don't recommend..." button
  + "Don't recommend" button  : it shows a new panel of reports (in order to report violated videos) as the seenshot above.

It's very easy to reproduce this bug on Firefox, so you can try. This makes very inconvenient.

**Comment by lozog** [comment] 2024-09-17 14:33
@binhnguyenvo I have been unable to reproduce any of the issues you're reported, unfortunately. With the same version of firefox and the same language as you, the plugin is working correctly for me.
I'll have to add some debugging to the extension to try and glean more info from this. It's difficult to fix without seeing any obvious problems from your reports.

**Comment by binhnguyenvo** [comment] 2024-09-18 04:00
I've recorded my screen of this bug for your reference on my side (Firefox). Both buttons (X and thumb down buttons) works improperly.

<iframe src="https://hqq.ac/e/THlUY0JmS2JreElPbGlXenFMNmNRQT09" height="450" width="720" webkitAllowFullScreen mozallowfullscreen allowfullscreen frameborder="0" scrolling="no"></iframe>

**Comment by lozog** [comment] 2024-09-19 01:44
@binhnguyenvo would you be able to record your screen for the bug, but also show the three dots menu on the videos?

The extension relies on that menu having the "hide" and "don't recommend channel" buttons in that menu be in certain locations. I'd like to verify that this assumption is correct. Perhaps it's changing on your end, for some reason.

**Comment by binhnguyenvo** [comment] 2024-09-19 12:25
I've recorded a new video once again for this bug here:

https://waaw.ac/f/U24nGfcSCl9a

    1.  Bug 1:  Some videos (especially, the channels that have never been visited before) have wrong behaviors of 2 buttons: X and Thumb Down, whereas other videos on the same youtube page have correct button behaviors.
    2.  Bug 2:  For PREMERE Videos: it always gets improperly working all the time for these premier videos.

**Comment by lozog** [comment] 2024-09-21 19:30
@binhnguyenvo thanks for that
I'm going to try adding some debugging tools to the extension. In the meantime, you can try disabling all extensions and only turning on this one to see if it's conflicting with one of those.

**Comment by binhnguyenvo** [comment] 2024-09-22 10:20
Hi, the video recorded above was performed when I disabled all other extensions on my Firefox. I thought it may conflct with others, so I turned other extensions off. But the issues still remain.

**Comment by binhnguyenvo** [comment] 2024-09-22 12:24
Hey, I've just recorded a new video once again with other extensions disabled. Now is Sep-22 night. Hope it helps.

https://waaw.ac/f/Pkmt536whP8Q

**Comment by lozog** [comment] 2024-09-23 16:52
@binhnguyenvo i released a new version of the extension (1.2). I added an option for debugging. Could you update to this version, enable debugging, go to youtube, open the console, then click on the buttons. Please share what is logged to the console. it should look like this:
![Screenshot 2024-09-23 at 12 51 42](https://github.com/user-attachments/assets/974806e2-d7b6-4308-b127-a9b05f1ebfd1)

**Comment by binhnguyenvo** [comment] 2024-09-24 03:24
This is a new recorded video with console logs in debugging mode. I've also disabled other extensions. Both issues of "Don't recommend channel" and PREMIER videos still remain:

https://waaw.ac/f/sXjCPu6x8GRO

Screen shot:
https://imgur.com/a/8c0jzMe

**Comment by binhnguyenvo** [comment] 2024-09-24 04:28
I found this clue in recent debugging: it may be that the missing of Download button in context menu is the root cause as this image:

![Uploading 555.png…]()

**Comment by lozog** [comment] 2024-09-24 19:12
ah! very interesting. i wonder about the behaviour of this Download option - it shows up in the list for me even if it isn't rendered, yet for you it seems that some videos do not have it in the list at all.
Looking into it a bit more, perhaps it changes depending on region. 

I want to make this more robust - if youtube changes their layout, this will keep breaking. But let me try to implement a fix for now.

**Comment by lozog** [comment] 2024-09-24 19:20
In your first screenshot, the first console output is weird - the list has "bao vi pham" twice. This might indicate that there is another issue also happening.

**Comment by binhnguyenvo** [comment] 2024-09-25 04:25
Yep especially for Premier videos. Hope to see your next release.

**Comment by lozog** [comment] 2024-09-27 03:42
@binhnguyenvo I have a 1.3 release candidate [here](https://github.com/lozog/not-interested-youtube/releases/tag/1.3-rc.1). you can try it and see if it resolves any issues

**Comment by binhnguyenvo** [comment] 2024-09-27 04:11
I cannot install your candidate version on my Firefox 130.0.1 (64-bit).
It warns the addon is not verified.
I have changed firefox settings to FALSE but it still cannot allow to install:

**xpinstall.signatures.required
extensions.langpacks.signatures.required**

**Comment by lozog** [comment] 2024-09-27 14:57
you can go to the `about:debugging#/runtime/this-firefox` page and use the "Load Temporary Add-on" feature. it should let you install from the source without signatures.

**Comment by binhnguyenvo** [comment] 2024-09-28 03:30
I've tried your 1.3 version, but issues still remain for 2 options, especially for videos without Download button.

**Comment by lozog** [comment] 2024-09-29 14:38
I'll take your suggestions into consideration. In the meantime, I'll be closing this issue, as the bug is resolved as of version 1.3

**Closed by lozog** 2024-09-29 14:38 UTC
